services:
  # Backend API service
  - type: web
    name: banking-system-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: Bank
      - key: JWT_SECRET
        generateValue: true

  # Frontend static site
  - type: web
    name: banking-system-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VUE_APP_API_URL
        value: https://banking-system-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
